spring.application.name=account-service
server.port=8081

spring.datasource.url=jdbc:postgresql://billing_postgres:5432/account_db
spring.datasource.username=billing_user
spring.datasource.password=billing_password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://keycloak:8080/realms/billing-realm/protocol/openid-connect/certs
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8180/realms/billing-realm

keycloak.server-url=http://keycloak:8080
keycloak.realm=billing-realm
keycloak.client-id=account-service
keycloak.client-secret=${KEYCLOAK_CLIENT_SECRET}

logging.level.org.springframework.security=DEBUG
