server.port=8083
spring.application.name=api-gateway

spring.data.redis.host=gateway_redis
spring.data.redis.port=6379

spring.cloud.gateway.server.webflux.routes[0].id=account-service
spring.cloud.gateway.server.webflux.routes[0].uri=http://account-service:8081
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/accounts/**
spring.cloud.gateway.server.webflux.routes[1].filters[0].name=RequestRateLimiter
spring.cloud.gateway.server.webflux.routes[1].filters[0].args.key-resolver=#{@userKeyResolver}
spring.cloud.gateway.server.webflux.routes[1].filters[0].args.redis-rate-limiter.replenishRate=5
spring.cloud.gateway.server.webflux.routes[1].filters[0].args.redis-rate-limiter.burstCapacity=10
#spring.cloud.gateway.server.webflux.routes[1].filters[0].args.throw-on-limit=true

spring.cloud.gateway.server.webflux.routes[1].id=billing-service
spring.cloud.gateway.server.webflux.routes[1].uri=http://billing-service:8080
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/plans/**,/api/subscriptions/**,/api/invoices/**,/api/payment-attempts/**,/api/subscription-activities/**,/api/churn-risk/**
spring.cloud.gateway.server.webflux.routes[0].filters[0].name=RequestRateLimiter
spring.cloud.gateway.server.webflux.routes[0].filters[0].args.key-resolver=#{@userKeyResolver}
spring.cloud.gateway.server.webflux.routes[0].filters[0].args.redis-rate-limiter.replenishRate=5
spring.cloud.gateway.server.webflux.routes[0].filters[0].args.redis-rate-limiter.burstCapacity=10

management.endpoints.web.exposure.include=health,info,gateway
management.endpoint.gateway.access=read-only

# CORS configuration
spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowedOrigins=http://localhost:5173
spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowedMethods=GET,POST,PUT,DELETE,OPTIONS
spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowedHeaders=*
spring.cloud.gateway.server.webflux.globalcors.add-to-simple-url-handler-mapping=true

# Keycloak JWT validation
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://keycloak:8080/realms/billing-realm/protocol/openid-connect/certs
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8180/realms/billing-realm